# GitHub Actions Linting Configuration for actionlint
# https://github.com/rhysd/actionlint

# Shellcheck configuration
shellcheck:
  # Enable all shellcheck checks
  enable: true

# pyflakes configuration for Python scripts in actions
pyflakes:
  enable: true

# Permissions checking
permissions: warning

# Allow expressions in workflow_dispatch inputs
config-variables: true

